### Traer todos los productos
GET https://rest-api-deploy-1azc.onrender.com/productos

### tarer un producto por su ID
GET https://rest-api-deploy-1azc.onrender.com/productos/3
### filtrar por categoria 
GET https://rest-api-deploy-1azc.onrender.com/productos?categoria=electronics

### Crear un nuevo producto
POST https://rest-api-deploy-1azc.onrender.com/productos
Content-Type: application/json

{
    "title": "Chaqueta de cuero",
    "price": 520,
    "description": "Chaqueta de cuero de alta calidad",
    "category": "Putas",
    "image": "https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_t.png",
    "rating": {
     
    }
  }

### Modificar Parcialmente un recurso
PATCH https://rest-api-deploy-1azc.onrender.com/productos/698a623d6685bc72b4fdf6d7
Content-Type: application/json

{
  "price": 200
}

### Eliminar un producto 
DELETE https://rest-api-deploy-1azc.onrender.com/productos/698a623d6685bc72b4fdf6d7